### ISSUE TITLE
Croptopia cannot be load in Fabric 1.21.4

### ISSUE THREAD

**Issue by 837cyo84o2rcj** [ExcessiveAmountsOfZombies/Croptopia#675]
I want to add Croptopia for my server. I downloaded the Croptopia-1.21-FABRIC-3.0.9.jar and EpheroLib-FABRIC-1.2.0-1.21.jar, then I put them in my server's mod folder. At first, the server loads normally, but about 4 to 5 seconds later, the server suddenly stopped. The error report thrown by the server is as follow. 

[Uploading err.txt…]()

**Comment by 837cyo84o2rcj** [comment]
If the txt file is unavailable, here's the message:

[20:41:42] [main/ERROR]: Failed to start the minecraft server[20:41:42] [main/ERROR]: Failed to start the minecraft serverjava.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'croptopia' at 'com.epherical.croptopia.Croptopia'! at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?] at knot/net.minecraft.server.Main.main(Main.java:113) [server-intermediary.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?] at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.4.jar:1.0.1]Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1798 at knot/com.epherical.croptopia.Croptopia.onInitialize(Croptopia.java:68) ~[Croptopia-1.21-FABRIC-3.0.9.jar:?] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?] ... 7 moreCaused by: java.lang.ClassNotFoundException: net.minecraft.class_1798 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] at knot/com.epherical.croptopia.Croptopia.onInitialize(Croptopia.java:68) ~[Croptopia-1.21-FABRIC-3.0.9.jar:?] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?] ... 7 more

**Comment by ExcessiveAmountsOfZombies** [comment]
yea... croptopia wont work on fabric in 1.21.4, sorry about that I don't have the time to maintain fabric versions anymore
